spring:
  datasource:
    url: jdbc:mysql://192.168.121.129:3306/dbname
    username: root
    password: 123456
    driver-class-name: org.gjt.mm.mysql.Driver
    
mybatis:
  # 配置映射类所在包名
  type-aliases-package: com.bootweb.entity
  # 配置mapper xml文件所在路径，这里是一个数组
  mapper-locations: classpath:com/bootweb/mapping/*.xml
  
